version: "3.8"

services:
  postgres-db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bdmeuapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456  # Consider using a more secure password management strategy

  spring-app:
    image: backend-cadastro-pessoa:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/bdmeuapp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
    depends_on:
      - postgres-db

  spa-app:
    build:
      context: ./cadastro-pessoa
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - spring-app